window.eagleSafeProducts = [
  {
    "model": "DDMT1",
    "category": "double-door",
    "categoryName": "Double Door",
    "image": "image/product_Image/double_door/DDMT1/image1.png",
    "page": "product_pages/double_door/DDMT1/DDMT1.html",
    "outerHeightInches": 78,
    "outerWidthInches": 48,
    "outerDepthInches": 30,
    "weightKg": 2200,
    "volumeLitres": 1840,
    "modelType": "DEFENDER PRIME"
  },
  {
    "model": "DDMT2",
    "category": "double-door",
    "categoryName": "Double Door",
    "image": "image/product_Image/double_door/DDMT2/image1.png",
    "page": "product_pages/double_door/DDMT2/DDMT2.html",
    "outerHeightInches": 72,
    "outerWidthInches": 42,
    "outerDepthInches": 30,
    "weightKg": 2050,
    "volumeLitres": 1490,
    "modelType": "DEFENDER PLUS"
  },
  {
    "model": "DDMT3",
    "category": "double-door",
    "categoryName": "Double Door",
    "image": "image/product_Image/double_door/DDMT3/image1.png",
    "page": "product_pages/double_door/DDMT3/DDMT3.html",
    "outerHeightInches": 48,
    "outerWidthInches": 38,
    "outerDepthInches": 28,
    "weightKg": 1300,
    "volumeLitres": 840,
    "modelType": "DEFENDER PLUS"
  },
  {
    "model": "DDMT4",
    "category": "double-door",
    "categoryName": "Double Door",
    "image": "image/product_Image/double_door/DDMT4/image1.png",
    "page": "product_pages/double_door/DDMT4/DDMT4.html",
    "outerHeightInches": 61,
    "outerWidthInches": 40,
    "outerDepthInches": 28,
    "weightKg": 1700,
    "volumeLitres": 1120,
    "modelType": "CLASSIC DEFENDER PLUS"
  },
  {
    "model": "DDMT5",
    "category": "double-door",
    "categoryName": "Double Door",
    "image": "image/product_Image/double_door/DDMT5/image1.png",
    "page": "product_pages/double_door/DDMT5/DDMT5.html",
    "outerHeightInches": 78,
    "outerWidthInches": 42,
    "outerDepthInches": 30,
    "weightKg": 2500,
    "volumeLitres": 1610,
    "modelType": "DEFENDER PLUS"
  },
  {
    "model": "DDMT6",
    "category": "double-door",
    "categoryName": "Double Door",
    "image": "image/product_Image/double_door/DDMT6/image1.png",
    "page": "product_pages/double_door/DDMT6/DDMT6.html",
    "outerHeightInches": 42,
    "outerWidthInches": 36,
    "outerDepthInches": 28,
    "weightKg": 1100,
    "volumeLitres": 690,
    "modelType": "DEFENDER PLUS"
  },
  {
    "model": "DDMT7",
    "category": "double-door",
    "categoryName": "Double Door",
    "image": "image/product_Image/double_door/DDMT7/image1.png",
    "page": "product_pages/double_door/DDMT7/DDMT7.html",
    "outerHeightInches": 50,
    "outerWidthInches": 38,
    "outerDepthInches": 28,
    "weightKg": 1300,
    "volumeLitres": 870,
    "modelType": "DEFENDER PLUS"
  },
  {
    "model": "DDMT8",
    "category": "double-door",
    "categoryName": "Double Door",
    "image": "image/product_Image/double_door/DDMT8/image1.png",
    "page": "product_pages/double_door/DDMT8/DDMT8.html",
    "outerHeightInches": 45,
    "outerWidthInches": 36,
    "outerDepthInches": 25,
    "weightKg": 1100,
    "volumeLitres": 660,
    "modelType": "DEFENDER PLUS"
  },
  {
    "model": "DDMT9",
    "category": "double-door",
    "categoryName": "Double Door",
    "image": "image/product_Image/double_door/DDMT9/image1.png",
    "page": "product_pages/double_door/DDMT9/DDMT9.html",
    "outerHeightInches": 61,
    "outerWidthInches": 42,
    "outerDepthInches": 30,
    "weightKg": 1700,
    "volumeLitres": 1260,
    "modelType": "DEFENDER PLUS"
  },
  {
    "model": "DDMT10",
    "category": "double-door",
    "categoryName": "Double Door",
    "image": "image/product_Image/double_door/DDMT10/image1.png",
    "page": "product_pages/double_door/DDMT10/DDMT10.html",
    "outerHeightInches": 61,
    "outerWidthInches": 38,
    "outerDepthInches": 30,
    "weightKg": 1500,
    "volumeLitres": 1140,
    "modelType": "DEFENDER PLUS"
  },
  {
    "model": "DDMT11",
    "category": "double-door",
    "categoryName": "Double Door",
    "image": "image/product_Image/double_door/DDMT11/image1.png",
    "page": "product_pages/double_door/DDMT11/DDMT11.html",
    "outerHeightInches": 66,
    "outerWidthInches": 42,
    "outerDepthInches": 30,
    "weightKg": 1800,
    "volumeLitres": 1360,
    "modelType": "DEFENDER PLUS"
  },
  {
    "model": "DDMT12",
    "category": "double-door",
    "categoryName": "Double Door",
    "image": "image/product_Image/double_door/DDMT12/image1.png",
    "page": "product_pages/double_door/DDMT12/DDMT12.html",
    "outerHeightInches": 36,
    "outerWidthInches": 36,
    "outerDepthInches": 28,
    "weightKg": 800,
    "volumeLitres": 590,
    "modelType": "DEFENDER PLUS"
  },
  {
    "model": "LSMT1",
    "category": "large-safe",
    "categoryName": "Large Safe",
    "image": "image/product_Image/large/LSMT1/image1.png",
    "page": "product_pages/large/LSMT1/LSMT1.html",
    "outerHeightInches": 49,
    "outerWidthInches": 32,
    "outerDepthInches": 28,
    "weightKg": 1200,
    "volumeLitres": 720,
    "modelType": "DEFENDER PLUS"
  },
  {
    "model": "LSMT2",
    "category": "large-safe",
    "categoryName": "Large Safe",
    "image": "image/product_Image/large/LSMT2/image1.png",
    "page": "product_pages/large/LSMT2/LSMT2.html",
    "outerHeightInches": 61,
    "outerWidthInches": 35,
    "outerDepthInches": 28,
    "weightKg": 1500,
    "volumeLitres": 980,
    "modelType": "DEFENDER PLUS"
  },
  {
    "model": "LSMT3",
    "category": "large-safe",
    "categoryName": "Large Safe",
    "image": "image/product_Image/large/LSMT3/image1.png",
    "page": "product_pages/large/LSMT3/LSMT3.html",
    "outerHeightInches": 49,
    "outerWidthInches": 30,
    "outerDepthInches": 28,
    "weightKg": 1125,
    "volumeLitres": 670,
    "modelType": "DEFENDER PRIME"
  },
  {
    "model": "LSMT4",
    "category": "large-safe",
    "categoryName": "Large Safe",
    "image": "image/product_Image/large/LSMT4/Image1.png",
    "page": "product_pages/large/LSMT4/LSMT4.html",
    "outerHeightInches": 61,
    "outerWidthInches": 34,
    "outerDepthInches": 28,
    "weightKg": 1600,
    "volumeLitres": 950,
    "modelType": "DEFENDER PLUS"
  },
  {
    "model": "LSMT5",
    "category": "large-safe",
    "categoryName": "Large Safe",
    "image": "image/product_Image/large/LSMT5/Image1.png",
    "page": "product_pages/large/LSMT5/LSMT5.html",
    "outerHeightInches": 49,
    "outerWidthInches": 32,
    "outerDepthInches": 28,
    "weightKg": 1200,
    "volumeLitres": 720,
    "modelType": "DEFENDER PLUS"
  },
  {
    "model": "LSMT6",
    "category": "large-safe",
    "categoryName": "Large Safe",
    "image": "image/product_Image/large/LSMT6/image1.png",
    "page": "product_pages/large/LSMT6/LSMT6.html",
    "outerHeightInches": 61,
    "outerWidthInches": 34,
    "outerDepthInches": 28,
    "weightKg": 1600,
    "volumeLitres": 950,
    "modelType": "DEFENDER PLUS"
  },
  {
    "model": "LSMT7",
    "category": "large-safe",
    "categoryName": "Large Safe",
    "image": "image/product_Image/large/LSMT7/image1.png",
    "page": "product_pages/large/LSMT7/LSMT7.html",
    "outerHeightInches": 49,
    "outerWidthInches": 32,
    "outerDepthInches": 28,
    "weightKg": 1200,
    "volumeLitres": 720,
    "modelType": "DEFENDER PLUS"
  },
  {
    "model": "LSMT8",
    "category": "large-safe",
    "categoryName": "Large Safe",
    "image": "image/product_Image/large/LSMT8/image1.png",
    "page": "product_pages/large/LSMT8/LSMT8.html",
    "outerHeightInches": 50,
    "outerWidthInches": 33,
    "outerDepthInches": 30,
    "weightKg": 1350,
    "volumeLitres": 810,
    "modelType": "CLASSIC DEFENDER PLUS"
  },
  {
    "model": "LSMT9",
    "category": "large-safe",
    "categoryName": "Large Safe",
    "image": "image/product_Image/large/LSMT9/image1.png",
    "page": "product_pages/large/LSMT9/LSMT9.html",
    "outerHeightInches": 66,
    "outerWidthInches": 35,
    "outerDepthInches": 28,
    "weightKg": 1800,
    "volumeLitres": 1060,
    "modelType": "DEFENDER PLUS"
  },
  {
    "model": "LSMT10",
    "category": "large-safe",
    "categoryName": "Large Safe",
    "image": "image/product_Image/large/LSMT10/image1.png",
    "page": "product_pages/large/LSMT10/LSMT10.html",
    "outerHeightInches": 61,
    "outerWidthInches": 35,
    "outerDepthInches": 29,
    "weightKg": 1700,
    "volumeLitres": 1010,
    "modelType": "CLASSIC DEFENDER PLUS"
  },
  {
    "model": "LSMT11",
    "category": "large-safe",
    "categoryName": "Large Safe",
    "image": "image/product_Image/large/LSMT11/image1.png",
    "page": "product_pages/large/LSMT11/LSMT11.html",
    "outerHeightInches": 50,
    "outerWidthInches": 33,
    "outerDepthInches": 29,
    "weightKg": 1350,
    "volumeLitres": 780,
    "modelType": "CLASSIC DEFENDER PLUS"
  },
  {
    "model": "LSMT12",
    "category": "large-safe",
    "categoryName": "Large Safe",
    "image": "image/product_Image/large/LSMT12/image1.png",
    "page": "product_pages/large/LSMT12/LSMT12.html",
    "outerHeightInches": 49,
    "outerWidthInches": 25,
    "outerDepthInches": 25,
    "weightKg": 900,
    "volumeLitres": 500,
    "modelType": "DEFENDER PLUS"
  },
  {
    "model": "LSMT13",
    "category": "large-safe",
    "categoryName": "Large Safe",
    "image": "image/product_Image/large/LSMT13/image1.png",
    "page": "product_pages/large/LSMT13/LSMT13.html",
    "outerHeightInches": 49,
    "outerWidthInches": 25,
    "outerDepthInches": 25,
    "weightKg": 900,
    "volumeLitres": 500,
    "modelType": "DEFENDER PLUS"
  },
  {
    "model": "LSMT14",
    "category": "large-safe",
    "categoryName": "Large Safe",
    "image": "image/product_Image/large/LSMT14/image1.png",
    "page": "product_pages/large/LSMT14/LSMT14.html",
    "outerHeightInches": 61,
    "outerWidthInches": 34,
    "outerDepthInches": 28,
    "weightKg": 1500,
    "volumeLitres": 950,
    "modelType": "DEFENDER PLUS"
  },
  {
    "model": "LSMT15",
    "category": "large-safe",
    "categoryName": "Large Safe",
    "image": "image/product_Image/large/LSMT15/image1.png",
    "page": "product_pages/large/LSMT15/LSMT15.html",
    "outerHeightInches": 61,
    "outerWidthInches": 34,
    "outerDepthInches": 28,
    "weightKg": 1500,
    "volumeLitres": 950,
    "modelType": "DEFENDER PLUS"
  },
  {
    "model": "LSMT16",
    "category": "large-safe",
    "categoryName": "Large Safe",
    "image": "image/product_Image/large/LSMT16/image1.png",
    "page": "product_pages/large/LSMT16/LSMT16.html",
    "outerHeightInches": 49,
    "outerWidthInches": 32,
    "outerDepthInches": 28,
    "weightKg": 1200,
    "volumeLitres": 720,
    "modelType": "DEFENDER PLUS"
  },
  {
    "model": "LSMT17",
    "category": "large-safe",
    "categoryName": "Large Safe",
    "image": "image/product_Image/large/LSMT17/image1.png",
    "page": "product_pages/large/LSMT17/LSMT17.html",
    "outerHeightInches": 50,
    "outerWidthInches": 33,
    "outerDepthInches": 30,
    "weightKg": 1350,
    "volumeLitres": 810,
    "modelType": "CLASSIC DEFENDER PLUS"
  },
  {
    "model": "MSMT1",
    "category": "medium-safe",
    "categoryName": "Medium Safe",
    "image": "image/product_Image/medium/MSMT1/image1.png",
    "page": "product_pages/medium/MSMT1/MSMT1.html",
    "outerHeightInches": 36,
    "outerWidthInches": 27,
    "outerDepthInches": 27,
    "weightKg": 700,
    "volumeLitres": 430,
    "modelType": "DEFENDER PLUS"
  },
  {
    "model": "MSMT2",
    "category": "medium-safe",
    "categoryName": "Medium Safe",
    "image": "image/product_Image/medium/MSMT2/image1.png",
    "page": "product_pages/medium/MSMT2/MSMT2.html",
    "outerHeightInches": 36,
    "outerWidthInches": 27,
    "outerDepthInches": 27,
    "weightKg": 650,
    "volumeLitres": 430,
    "modelType": "DEFENDER PRIME"
  },
  {
    "model": "MSMT3",
    "category": "medium-safe",
    "categoryName": "Medium Safe",
    "image": "image/product_Image/medium/MSMT3/image1.png",
    "page": "product_pages/medium/MSMT3/MSMT3.html",
    "outerHeightInches": 36,
    "outerWidthInches": 27,
    "outerDepthInches": 27,
    "weightKg": 500,
    "volumeLitres": 430,
    "modelType": "DEFENDER PRIME"
  },
  {
    "model": "MSMT4",
    "category": "medium-safe",
    "categoryName": "Medium Safe",
    "image": "image/product_Image/medium/MSMT4/Image1.png",
    "page": "product_pages/medium/MSMT4/MSMT4.html",
    "outerHeightInches": 42,
    "outerWidthInches": 30,
    "outerDepthInches": 28,
    "weightKg": 1000,
    "volumeLitres": 580,
    "modelType": "DEFENDER PLUS"
  },
  {
    "model": "MSMT5",
    "category": "medium-safe",
    "categoryName": "Medium Safe",
    "image": "image/product_Image/medium/MSMT5/image1.png",
    "page": "product_pages/medium/MSMT5/MSMT5.html",
    "outerHeightInches": 36,
    "outerWidthInches": 24,
    "outerDepthInches": 24,
    "weightKg": 500,
    "volumeLitres": 340,
    "modelType": "DEFENDER PRIME"
  },
  {
    "model": "MSMT6",
    "category": "medium-safe",
    "categoryName": "Medium Safe",
    "image": "image/product_Image/medium/MSMT6/image1.png",
    "page": "product_pages/medium/MSMT6/MSMT6.html",
    "outerHeightInches": 36,
    "outerWidthInches": 27,
    "outerDepthInches": 27,
    "weightKg": 800,
    "volumeLitres": 430,
    "modelType": "DEFENDER PLUS"
  },
  {
    "model": "MSMT7",
    "category": "medium-safe",
    "categoryName": "Medium Safe",
    "image": "image/product_Image/medium/MSMT7/image1.png",
    "page": "product_pages/medium/MSMT7/MSMT7.html",
    "outerHeightInches": 36,
    "outerWidthInches": 24,
    "outerDepthInches": 24,
    "weightKg": 500,
    "volumeLitres": 340,
    "modelType": "DEFENDER PRIME"
  },
  {
    "model": "MSMT8",
    "category": "medium-safe",
    "categoryName": "Medium Safe",
    "image": "image/product_Image/medium/MSMT8/image1.png",
    "page": "product_pages/medium/MSMT8/MSMT8.html",
    "outerHeightInches": 30,
    "outerWidthInches": 22,
    "outerDepthInches": 22,
    "weightKg": 350,
    "volumeLitres": 240,
    "modelType": "DEFENDER PLUS"
  },
  {
    "model": "MSMT9",
    "category": "medium-safe",
    "categoryName": "Medium Safe",
    "image": "image/product_Image/medium/MSMT9/image1.png",
    "page": "product_pages/medium/MSMT9/MSMT9.html",
    "outerHeightInches": 36,
    "outerWidthInches": 27,
    "outerDepthInches": 27,
    "weightKg": 800,
    "volumeLitres": 430,
    "modelType": "DEFENDER PLUS"
  },
  {
    "model": "SSMT1",
    "category": "small-safe",
    "categoryName": "Small Safe",
    "image": "image/product_Image/small/SSMT1/image1.jpg",
    "page": "product_pages/small/SSMT1/SSMT1.html",
    "outerHeightInches": 24,
    "outerWidthInches": 16,
    "outerDepthInches": 16,
    "weightKg": 0,
    "volumeLitres": 100,
    "modelType": "OTHERS"
  },
  {
    "model": "SSMT2",
    "category": "small-safe",
    "categoryName": "Small Safe",
    "image": "image/product_Image/small/SSMT2/image1.jpg",
    "page": "product_pages/small/SSMT2/SSMT2.html",
    "outerHeightInches": 16,
    "outerWidthInches": 20,
    "outerDepthInches": 16,
    "weightKg": 0,
    "volumeLitres": 80,
    "modelType": "OTHERS"
  },
  {
    "model": "SSMT3",
    "category": "small-safe",
    "categoryName": "Small Safe",
    "image": "image/product_Image/small/SSMT3/image1.png",
    "page": "product_pages/small/SSMT3/SSMT3.html",
    "outerHeightInches": 10,
    "outerWidthInches": 14,
    "outerDepthInches": 10,
    "weightKg": 0,
    "volumeLitres": 20,
    "modelType": "OTHERS"
  },
  {
    "model": "CLMT2",
    "category": "counter-locker",
    "categoryName": "Counter Locker",
    "image": "image/product_Image/counter_locker/CLMT2/image1.png",
    "page": "product_pages/counter_locker/CLMT2/CLMT2.html",
    "outerHeightInches": 30,
    "outerWidthInches": 42,
    "outerDepthInches": 24,
    "weightKg": 850,
    "volumeLitres": 500,
    "modelType": "DEFENDER PLUS"
  },
  {
    "model": "CLMT3",
    "category": "counter-locker",
    "categoryName": "Counter Locker",
    "image": "image/product_Image/counter_locker/CLMT3/image1.png",
    "page": "product_pages/counter_locker/CLMT3/CLMT3.html",
    "outerHeightInches": 30,
    "outerWidthInches": 72,
    "outerDepthInches": 24,
    "weightKg": 1800,
    "volumeLitres": 850,
    "modelType": "DEFENDER PLUS"
  },
  {
    "model": "CLMT4",
    "category": "counter-locker",
    "categoryName": "Counter Locker",
    "image": "image/product_Image/counter_locker/CLMT4/image1.png",
    "page": "product_pages/counter_locker/CLMT4/CLMT4.html",
    "outerHeightInches": 30,
    "outerWidthInches": 90,
    "outerDepthInches": 24,
    "weightKg": 2200,
    "volumeLitres": 1060,
    "modelType": "DEFENDER PLUS"
  },
  {
    "model": "TDMT1",
    "category": "triple-door",
    "categoryName": "Triple Door",
    "image": "image/product_Image/triple_door/TDMT1/image1.png",
    "page": "product_pages/triple_door/TDMT1/TDMT1.html",
    "outerHeightInches": 78,
    "outerWidthInches": 72,
    "outerDepthInches": 31,
    "weightKg": 3800,
    "volumeLitres": 2850,
    "modelType": "DEFENDER PRIME"
  },
  {
    "model": "TDMT2",
    "category": "triple-door",
    "categoryName": "Triple Door",
    "image": "image/product_Image/triple_door/TDMT2/image1.png",
    "page": "product_pages/triple_door/TDMT2/TDMT2.html",
    "outerHeightInches": 66,
    "outerWidthInches": 72,
    "outerDepthInches": 30,
    "weightKg": 3000,
    "volumeLitres": 2340,
    "modelType": "DEFENDER PRIME"
  }
];
